spring:
  application:
    name: "db_mcp_server"
  # Spring AI MCP配置
  ai:
    mcp:
      server:
        enabled: true
        sse-endpoint: /sse
        name: db-mcp-server
        version: 1.0.0
        sse-message-endpoint: /mcp/message
        capabilities:
          tool: true

server:
  port: 8088
